spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/ceiba
    driver: com.mysql.Driver
    username: root
    password: ceiba
    testWhileIdle: true
    validationQuery: SELECT 1
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: validate
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      dialect: org.hibernate.dialect.MySQL5Dialect
