spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ceiba
    driver: com.mysql.Driver
    username: root
    password: ceiba
    testWhileIdle: true
    validationQuery: SELECT 1
  flyway:
    baselineOnMigrate: true

security:
  jwt:
    token:
      expire-length: 3600000
      secret-key: supersecretkey
